// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookings.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelBooking = `-- name: CancelBooking :exec
UPDATE bookings
SET status = 'canceled'
WHERE id = $1 AND user_id = $2 AND status = 'reserved'
`

type CancelBookingParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) CancelBooking(ctx context.Context, arg CancelBookingParams) error {
	_, err := q.db.Exec(ctx, cancelBooking, arg.ID, arg.UserID)
	return err
}

const cancelExpiredBookings = `-- name: CancelExpiredBookings :execrows
UPDATE bookings
SET status = 'canceled'
WHERE status = 'reserved' 
  AND expires_at < NOW()
`

func (q *Queries) CancelExpiredBookings(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cancelExpiredBookings)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (user_id, seat_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, seat_id, status, created_at, expires_at
`

type CreateBookingParams struct {
	UserID    uuid.UUID
	SeatID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking, arg.UserID, arg.SeatID, arg.ExpiresAt)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeatID,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, user_id, seat_id, status, created_at, expires_at FROM bookings
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetBookingByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetBookingByID(ctx context.Context, arg GetBookingByIDParams) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, arg.ID, arg.UserID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeatID,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getBookingsByUserID = `-- name: GetBookingsByUserID :many
SELECT id, user_id, seat_id, status, created_at, expires_at FROM bookings
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetBookingsByUserID(ctx context.Context, userID uuid.UUID) ([]Booking, error) {
	rows, err := q.db.Query(ctx, getBookingsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SeatID,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBookingStatusPaid = `-- name: SetBookingStatusPaid :exec
UPDATE bookings
SET status = 'paid'
WHERE id = $1 AND status = 'reserved'
`

func (q *Queries) SetBookingStatusPaid(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setBookingStatusPaid, id)
	return err
}
