// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getEventByID = `-- name: GetEventByID :one
SELECT id, title, description, location, start_time, created_at, end_time FROM events
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.CreatedAt,
		&i.EndTime,
	)
	return i, err
}

const getEvents = `-- name: GetEvents :many
SELECT id, title, description, location, start_time, created_at, end_time FROM events
ORDER BY start_time ASC
`

func (q *Queries) GetEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.CreatedAt,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeatsByEventWithBookings = `-- name: GetSeatsByEventWithBookings :many
SELECT 
    s.id AS seat_id, 
    s.event_id, 
    s.row, 
    s.number, 
    s.price,
    b.id AS booking_id, 
    b.user_id AS booking_user_id, 
    b.status AS booking_status, 
    b.expires_at AS booking_expires_at
FROM seats s
LEFT JOIN bookings b ON s.id = b.seat_id 
    AND b.status != 'canceled'
WHERE s.event_id = $1
ORDER BY s.row, s.number
`

type GetSeatsByEventWithBookingsRow struct {
	SeatID           uuid.UUID
	EventID          uuid.UUID
	Row              int32
	Number           int32
	Price            int32
	BookingID        uuid.UUID
	BookingUserID    uuid.UUID
	BookingStatus    NullBookingStatus
	BookingExpiresAt *time.Time
}

func (q *Queries) GetSeatsByEventWithBookings(ctx context.Context, eventID uuid.UUID) ([]GetSeatsByEventWithBookingsRow, error) {
	rows, err := q.db.Query(ctx, getSeatsByEventWithBookings, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeatsByEventWithBookingsRow
	for rows.Next() {
		var i GetSeatsByEventWithBookingsRow
		if err := rows.Scan(
			&i.SeatID,
			&i.EventID,
			&i.Row,
			&i.Number,
			&i.Price,
			&i.BookingID,
			&i.BookingUserID,
			&i.BookingStatus,
			&i.BookingExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
