// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type BookingStatus string

const (
	BookingStatusReserved BookingStatus = "reserved"
	BookingStatusPaid     BookingStatus = "paid"
	BookingStatusCanceled BookingStatus = "canceled"
)

func (e *BookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus
	Valid         bool // Valid is true if BookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type Booking struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	SeatID    uuid.UUID
	Status    BookingStatus
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Event struct {
	ID          uuid.UUID
	Title       string
	Description *string
	Location    *string
	StartTime   time.Time
	CreatedAt   time.Time
	EndTime     *time.Time
}

type Seat struct {
	ID      uuid.UUID
	EventID uuid.UUID
	Row     int32
	Number  int32
	Price   int32
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
